formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.
# installations will go into the standard /tmp/am hierarchy

applications:
  builtinAppsManifestDir: "${CONFIG_PWD}/apps"
  installedAppsManifestDir: "/tmp/triton-ui/manifests"
  appImageMountDir: "/tmp/triton-ui/image-mounts"
  database: "/tmp/triton-ui/apps.db"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "${CONFIG_PWD}/imports/shared" ]
    environmentVariables:
       QT_PLUGIN_PATH: ${CONFIG_PWD}
       SERVER_CONF_PATH: ${CONFIG_PWD}/server.conf
  native:
    importPaths: [ "${CONFIG_PWD}/imports/shared" ]
    environmentVariables:
      QT_PLUGIN_PATH: ${CONFIG_PWD}
      SERVER_CONF_PATH: ${CONFIG_PWD}/server.conf

# ... as well as the SystemUI

ui:
  fullscreen: no
  style: "${CONFIG_PWD}/styles/triton"
  mainQml: "${CONFIG_PWD}/Main.qml"
  importPaths: [ "${CONFIG_PWD}/imports/shared", "${CONFIG_PWD}/imports/system", "${CONFIG_PWD}/sysui" ]
  windowIcon: "${CONFIG_PWD}/imports/assets/icons/ic-menu-home.png"

systemProperties:
    public:
      showCluster: yes
      devMode: yes
    private:
      appStoreServerUrl: 'http://chaos.pelagicore.net:9090'
      orientation: 'Portrait'

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "/tmp/triton-ui/apps"
  documentPath: "/tmp/triton-ui/docs"
  mountPoint: "/tmp"
  isDefault: true
