formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.
# installations will go into the standard /tmp/am hierarchy

applications:
  builtinAppsManifestDir: "${CONFIG_PWD}/apps"
  installedAppsManifestDir: "/tmp/am/manifests"
  appImageMountDir: "/tmp/am/image-mounts"
  database: "/tmp/am/apps.db"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "${CONFIG_PWD}/imports/shared" ]

# ... as well as the SystemUI

ui:
  fullscreen: no
  style: "${CONFIG_PWD}/styles/triton"
  mainQml: "${CONFIG_PWD}/Main.qml"
  importPaths: [ "${CONFIG_PWD}/imports/shared", "${CONFIG_PWD}/imports/system", "${CONFIG_PWD}/sysui" ]
  windowIcon: "${CONFIG_PWD}/imports/assets/icons/active/apps@96.png"

systemProperties:
    public:
      showCluster: no
    private:
      appStoreServerUrl: 'http://chaos.pelagicore.net:8080'
      orientation: 'Portrait'

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "/tmp/am/apps"
  documentPath: "/tmp/am/docs"
  mountPoint: "/tmp"
  isDefault: true
