formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.
# installations will go into the standard QStandardPath AppLocalDataLocation
# (e.g. ~/.local/share/Luxoft Sweden AB/Neptune UI) /am hierarchy

applications:
  builtinAppsManifestDir: "${CONFIG_PWD}/apps"
  installedAppsManifestDir: "${stdpath:AppLocalDataLocation}/neptune3-ui/manifests"
  appImageMountDir: "${stdpath:AppLocalDataLocation}/neptune3-ui/image-mounts"
  database: "${stdpath:AppLocalDataLocation}/neptune3-ui/apps.db"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "${CONFIG_PWD}/imports_shared" ]
    environmentVariables:
       QT_PLUGIN_PATH: ${CONFIG_PWD}
       SERVER_CONF_PATH: ${CONFIG_PWD}/server.conf
       QT_FILE_SELECTORS: lucee
  native:
    importPaths: [ "${CONFIG_PWD}/imports_shared" ]
    environmentVariables:
      QT_PLUGIN_PATH: ${CONFIG_PWD}
      SERVER_CONF_PATH: ${CONFIG_PWD}/server.conf
      QT_FILE_SELECTORS: lucee

# ... as well as the SystemUI

ui:
  fullscreen: no
  style: "${CONFIG_PWD}/styles/lucee"
  iconThemeName: "lucee"
  iconThemeSearchPaths: [ "${CONFIG_PWD}/imports_shared/assets/icons" ]
  mainQml: "${CONFIG_PWD}/Main.qml"
  importPaths: [ "${CONFIG_PWD}/imports_shared", "${CONFIG_PWD}/imports_system", "${CONFIG_PWD}/sysui" ]
  windowIcon: "${CONFIG_PWD}/imports_shared/assets/icons/lucee/sysui/ic-menu-home.png"
  enableTouchEmulation: yes

systemProperties:
    public:
      showCluster: yes
      showHUD: yes
      devMode: yes
      enableCursorManagement: no
      hardwareVariant: 'high'
      #Qt Safe Renderer settings
      qsrEnabled: no
      qsrServerAddress: '127.0.0.1'
      qsrServerPort: '1111'
      showSystemAppsInLauncher: no
    private:
      appStoreServerUrl: 'http://chaos.pelagicore.net:9090'
      userName: 't'
      userPassword: 't'
      imei: '112163001487801'
      orientation: 'Portrait'
      adjustSizesForScreen: yes

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "${stdpath:AppLocalDataLocation}/neptune3-ui/apps"
  documentPath: "${stdpath:AppLocalDataLocation}/neptune3-ui/docs"
  mountPoint: "${stdpath:AppLocalDataLocation}"
  isDefault: true
